networks:
  caddy:
    name: caddy
    driver: bridge
    external: true

services:
  memos:
    image: neosmemo/memos:0.26
    restart: unless-stopped
    container_name: memos
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./data/app:/var/opt/memos
    networks:
      - caddy
